import {
  StyleSheet,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
} from "react-native";

import { useState } from "react";
import {
  Feather,
  MaterialCommunityIcons,
  MaterialIcons,
} from "@expo/vector-icons";
import axios from "axios";

export default function HomeScreen() {
  const [text, setText] = useState("");
  const [suggestions, setSuggestions] = useState([]);
  const [data, setData] = useState("");
  const [sunriseTime, setSunriseTime] = useState(null);
  const [sunsetTime, setSunsetTime] = useState(null);

  const words = [
    "Adoni",
    "Amaravati",
    "Anantapur",
    "Chandragiri",
    "Chittoor",
    "Dowlaiswaram",
    "Eluru",
    "Guntur",
    "Kadapa",
    "Kakinada",
    "Kurnool",
    "Machilipatnam",
    "Nagarjunakoṇḍa",
    "Rajahmundry",
    "Srikakulam",
    "Tirupati",
    "Vijayawada",
    "Visakhapatnam",
    "Vizianagaram",
    "Yemmiganur",
    "Itanagar",
    "Dhuburi",
    "Dibrugarh",
    "Dispur",
    "Guwahati",
    "Jorhat",
    "Nagaon",
    "Sivasagar",
    "Silchar",
    "Tezpur",
    "Tinsukia",
    "Ara",
    "Barauni",
    "Begusarai",
    "Bettiah",
    "Bhagalpur",
    "Bihar Sharif",
    "Bodh Gaya",
    "Buxar",
    "Chapra",
    "Darbhanga",
    "Dehri",
    "Dinapur Nizamat",
    "Gaya",
    "Hajipur",
    "Jamalpur",
    "Katihar",
    "Madhubani",
    "Motihari",
    "Munger",
    "Muzaffarpur",
    "Patna",
    "Purnia",
    "Pusa",
    "Saharsa",
    "Samastipur",
    "Sasaram",
    "Sitamarhi",
    "Siwan",
    "Chandigarh",
    "Ambikapur",
    "Bhilai",
    "Bilaspur",
    "Dhamtari",
    "Durg",
    "Jagdalpur",
    "Raipur",
    "Rajnandgaon",
    "Daman",
    "Diu",
    "Silvassa",
    "Delhi",
    "New Delhi",
    "Madgaon",
    "Panaji",
    "Ahmadabad",
    "Amreli",
    "Bharuch",
    "Bhavnagar",
    "Bhuj",
    "Dwarka",
    "Gandhinagar",
    "Godhra",
    "Jamnagar",
    "Junagadh",
    "Kandla",
    "Khambhat",
    "Kheda",
    "Mahesana",
    "Morbi",
    "Nadiad",
    "Navsari",
    "Okha",
    "Palanpur",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Surat",
    "Surendranagar",
    "Valsad",
    "Veraval",
    "Ambala",
    "Bhiwani",
    "Chandigarh",
    "Faridabad",
    "Firozpur Jhirka",
    "Gurugram",
    "Hansi",
    "Hisar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Panipat",
    "Pehowa",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Bilaspur",
    "Chamba",
    "Dalhousie",
    "Dharmshala",
    "Hamirpur",
    "Kangra",
    "Kullu",
    "Mandi",
    "Nahan",
    "Shimla",
    "Una",
    "Anantnag",
    "Baramula",
    "Doda",
    "Gulmarg",
    "Jammu",
    "Kathua",
    "Punch",
    "Rajouri",
    "Srinagar",
    "Udhampur",
    "Bokaro",
    "Chaibasa",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "Giridih",
    "Hazaribag",
    "Jamshedpur",
    "Jharia",
    "Rajmahal",
    "Ranchi",
    "Saraikela",
    "Badami",
    "Ballari",
    "Bengaluru",
    "Belagavi",
    "Bhadravati",
    "Bidar",
    "Chikkamagaluru",
    "Chitradurga",
    "Davangere",
    "Halebid",
    "Hassan",
    "Hubballi-Dharwad",
    "Kalaburagi",
    "Kolar",
    "Madikeri",
    "Mandya",
    "Mangaluru",
    "Mysuru",
    "Raichur",
    "Shivamogga",
    "Shravanabelagola",
    "Shrirangapattana",
    "Tumakuru",
    "Vijayapura",
    "Alappuzha",
    "Vatakara",
    "Idukki",
    "Kannur",
    "Kochi",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Mattancheri",
    "Palakkad",
    "Thalassery",
    "Thiruvananthapuram",
    "Thrissur",
    "Kargil",
    "Leh",
    "Balaghat",
    "Barwani",
    "Betul",
    "Bharhut",
    "Bhind",
    "Bhojpur",
    "Bhopal",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dr. Ambedkar Nagar (Mhow)",
    "Guna",
    "Gwalior",
    "Hoshangabad",
    "Indore",
    "Itarsi",
    "Jabalpur",
    "Jhabua",
    "Khajuraho",
    "Khandwa",
    "Khargone",
    "Maheshwar",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Murwara",
    "Narsimhapur",
    "Narsinghgarh",
    "Narwar",
    "Neemuch",
    "Nowgong",
    "Orchha",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Sarangpur",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Ujjain",
    "Vidisha",
    "Ahmadnagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Bhandara",
    "Bhusawal",
    "Bid",
    "Buldhana",
    "Chandrapur",
    "Daulatabad",
    "Dhule",
    "Jalgaon",
    "Kalyan",
    "Karli",
    "Kolhapur",
    "Mahabaleshwar",
    "Malegaon",
    "Matheran",
    "Mumbai",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Osmanabad",
    "Pandharpur",
    "Parbhani",
    "Pune",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sevagram",
    "Solapur",
    "Thane",
    "Ulhasnagar",
    "Vasai-Virar",
    "Wardha",
    "Yavatmal",
    "Imphal",
    "Cherrapunji",
    "Shillong",
    "Aizawl",
    "Lunglei",
    "Kohima",
    "Mon",
    "Phek",
    "Wokha",
    "Zunheboto",
    "Balangir",
    "Baleshwar",
    "Baripada",
    "Bhubaneshwar",
    "Brahmapur",
    "Cuttack",
    "Dhenkanal",
    "Kendujhar",
    "Konark",
    "Koraput",
    "Paradip",
    "Phulabani",
    "Puri",
    "Sambalpur",
    "Udayagiri",
    "",
    "Karaikal",
    "Mahe",
    "Puducherry",
    "Yanam",
    "Amritsar",
    "Batala",
    "Chandigarh",
    "Faridkot",
    "Firozpur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Nabha",
    "Patiala",
    "Rupnagar",
    "Sangrur",
    "Abu",
    "Ajmer",
    "Alwar",
    "Amer",
    "Barmer",
    "Beawar",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittaurgarh",
    "Churu",
    "Dhaulpur",
    "Dungarpur",
    "Ganganagar",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jalor",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Kishangarh",
    "Kota",
    "Merta",
    "Nagaur",
    "Nathdwara",
    "Pali",
    "Phalodi",
    "Pushkar",
    "Sawai Madhopur",
    "Shahpura",
    "Sikar",
    "Sirohi",
    "Tonk",
    "Udaipur",
    "",
    "Sikkim",
    "",
    "Gangtok",
    "Gyalshing",
    "Lachung",
    "Mangan",
    "",
    "Tamil Nadu",
    "",
    "Arcot",
    "Chengalpattu",
    "Chennai",
    "Chidambaram",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kanchipuram",
    "Kanniyakumari",
    "Kodaikanal",
    "Kumbakonam",
    "Madurai",
    "Mamallapuram",
    "Nagappattinam",
    "Nagercoil",
    "Palayamkottai",
    "Pudukkottai",
    "Rajapalayam",
    "Ramanathapuram",
    "Salem",
    "Thanjavur",
    "Tiruchchirappalli",
    "Tirunelveli",
    "Tiruppur",
    "Thoothukudi",
    "Udhagamandalam",
    "Vellore",
    "Hyderabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Nizamabad",
    "Sangareddi",
    "Warangal",
    "Agartala",
    "Agra",
    "Aligarh",
    "Amroha",
    "Ayodhya",
    "Azamgarh",
    "Bahraich",
    "Ballia",
    "Banda",
    "Bara Banki",
    "Bareilly",
    "Basti",
    "Bijnor",
    "Bithur",
    "Budaun",
    "Bulandshahr",
    "Deoria",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farrukhabad-cum-Fatehgarh",
    "Fatehpur",
    "Fatehpur Sikri",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur",
    "Lakhimpur",
    "Lalitpur",
    "Lucknow",
    "Mainpuri",
    "Mathura",
    "Meerut",
    "Mirzapur-Vindhyachal",
    "Moradabad",
    "Muzaffarnagar",
    "Partapgarh",
    "Pilibhit",
    "Prayagraj",
    "Rae Bareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Shahjahanpur",
    "Sitapur",
    "Sultanpur",
    "Tehri",
    "Varanasi",
    "Almora",
    "Dehra Dun",
    "Haridwar",
    "Mussoorie",
    "Nainital",
    "Pithoragarh",
    "Alipore",
    "Alipur Duar",
    "Asansol",
    "Baharampur",
    "Bally",
    "Balurghat",
    "Bankura",
    "Baranagar",
    "Barasat",
    "Barrackpore",
    "Basirhat",
    "Bhatpara",
    "Bishnupur",
    "Budge Budge",
    "Burdwan",
    "Chandernagore",
    "Darjeeling",
    "Diamond Harbour",
    "Dum Dum",
    "Durgapur",
    "Halisahar",
    "Haora",
    "Hugli",
    "Ingraj Bazar",
    "Jalpaiguri",
    "Kalimpong",
    "Kamarhati",
    "Kanchrapara",
    "Kharagpur",
    "Cooch Behar",
    "Kolkata",
    "Krishnanagar",
    "Malda",
    "Midnapore",
    "Murshidabad",
    "Nabadwip",
    "Palashi",
    "Panihati",
    "Purulia",
    "Raiganj",
    "Santipur",
    "Shantiniketan",
    "Shrirampur",
    "Siliguri",
    "Siuri",
    "Tamluk",
    "Titagarh",
  ];

  const onChangeText = (value) => {
    setText(value);
    if (value === "") {
      setSuggestions([]);
    } else {
      const matches = words.filter((word) =>
        word.toLowerCase().includes(value.toLowerCase())
      );
      setSuggestions(matches);
    }
  };

  const selectSuggestion = (word) => {
    setText(word);
    setSuggestions([]);
    fetchData(word);
  };

  const fetchData = async (city) => {
    try {
      const response = await axios.get(
        `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=fcb7d2efacb8077ca610dfe2f44e9224&units=metric`
      );
      setData(response.data);
      const unixSunrise = response.data.sys.sunrise;
      const sunriseDate = new Date(unixSunrise * 1000);
      const indianTime = sunriseDate.toLocaleTimeString("en-IN", {
        hour: "2-digit",
        minute: "2-digit",
        hour12: true,
        timeZone: "Asia/Kolkata",
      });
      setSunriseTime(indianTime);

      const unixsunset = response.data.sys.sunset;
      const sunsetDate = new Date(unixsunset * 1000);
      const indianTimeSunset = sunsetDate.toLocaleTimeString("en-IN", {
        hour: "2-digit",
        minute: "2-digit",
        hour12: true,
        timeZone: "Asia/Kolkata",
      });
      setSunsetTime(indianTimeSunset);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  return (
    <View>
      <Text style={styles.titleContainer}>Weather App</Text>
      <View style={styles.container}>
        <TextInput
          value={text}
          onChangeText={onChangeText}
          placeholder="Type city name..."
          style={styles.input}
        />

        <ScrollView>
          {suggestions.map((word, index) => (
            <TouchableOpacity
              key={index}
              onPress={() => selectSuggestion(word)}
            >
              <Text style={styles.suggestion}>{word}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>

        {data && text !== "" && (
          <View style={{ marginTop: 20 }}>
            <View style={styles.card}>
              <View style={styles.cardHeader}>
                <MaterialCommunityIcons
                  name="weather-cloudy"
                  size={90}
                  color="white"
                />
                <Text style={{ fontSize: 20, color: "white" }}>
                  {data.weather[0].description.toUpperCase()}
                </Text>

                <Text style={styles.temperatureText}>{data.main.temp}°C</Text>
                <Text style={styles.cityText}>{text}</Text>
              </View>
              <View style={styles.cardFooter}>
                <View style={styles.infoBox}>
                  <MaterialIcons name="water" size={50} color="white" />
                  <Text style={styles.infoText}>{data.main.humidity} %</Text>
                  <Text style={styles.infoLabel}>Humidity</Text>
                </View>
                <View style={styles.infoBox}>
                  <MaterialCommunityIcons
                    name="weather-windy"
                    size={50}
                    color="white"
                  />
                  <Text style={styles.infoText}>{data.wind.speed} m/s</Text>
                  <Text style={styles.infoLabel}>Wind Speed</Text>
                </View>
              </View>
              <View style={styles.cardFooter}>
                <View style={styles.infoBox}>
                  <Feather name="sunrise" size={50} color="white" />
                  <Text style={styles.infoText}>{sunriseTime}</Text>
                  <Text style={styles.infoLabel}>Sunrise</Text>
                </View>
                <View style={styles.infoBox}>
                  <Feather name="sunset" size={50} color="white" />
                  <Text style={styles.infoText}>{sunsetTime}</Text>
                  <Text style={styles.infoLabel}>Sunset</Text>
                </View>
              </View>
            </View>
          </View>
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 20,
  },
  input: {
    borderWidth: 1,
    padding: 10,
    borderRadius: 5,
    borderColor: "#aaa",
  },
  suggestion: {
    padding: 10,
    backgroundColor: "#eee",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  titleContainer: {
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    fontSize: 20,
    fontWeight: "bold",
    color: "#000",
    backgroundColor: "#fff",
    borderRadius: 10,
    margin: 10,
    marginTop: 50,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  card: {
    backgroundColor: "#4facfe",
    borderRadius: 20,
    padding: 20,
    marginVertical: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  cardHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  weatherIconLarge: {
    width: 100,
    height: 100,
    marginBottom: 10,
  },
  temperatureText: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#fff",
  },
  cityText: {
    fontSize: 24,
    fontWeight: "600",
    color: "#fff",
    marginTop: 5,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginTop: 20,
  },
  infoBox: {
    alignItems: "center",
    justifyContent: "center",
  },
  infoIcon: {
    width: 40,
    height: 40,
    marginBottom: 5,
  },
  infoText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  infoLabel: {
    fontSize: 14,
    color: "#fff",
  },
});
